---
- name: enable httpd
  systemd:
    name: httpd
    daemon_reload: yes
    enabled: yes

- name: start httpd
  systemd:
    name: httpd
    daemon_reload: yes
    state: started

- name: restart httpd
  systemd:
    name: httpd
    daemon_reload: yes
    state: restarted
...