---
- name: Copy certificates #required to connect the k8s cluster provisioned via chc-static playbook
  copy:
    src: "{{ playbook_dir }}/../certs/{{ item }}"
    dest: "{{ k8s_data_dir }}/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - ca.pem
  become: true

- name: download kubectl binaries
  get_url:
    url: "{{ k8s_release_url }}/{{ item }}"
    dest: "{{ kube_bin_dir }}/"
    mode: 0755
    owner: root
  with_items:
    - kubectl
  become: true

- name: Add kube configuration #copy kubeconfig for k8s cluster usage
  template:
    src: kubeconfig.j2
    dest: "{{ k8s_data_dir }}/kubeconfig"
    mode: 0644
  become: true
...