- hosts: webapp_host
  become: true

  pre_tasks:
  - name: get EC2 facts
    ec2_metadata_facts:
    ignore_errors: true
#  when: cloud_type is defined and cloud_type == "aws"

  roles:
    - { role: ssh-users, tags: ['users'] }
    - { role: git, tags: ['webapp_git'] }
    - { role: httpd, tags: ['webapp_httpd'] }